# Generated by Django 3.1.5 on 2021-01-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='porfile_pic',
            new_name='profile_pic',
        ),
    ]
